#!/usr/bin/bash
set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes

required_letter="${1:-}"
other_letters="${2:-}"

mvn --quiet exec:java -Dexec.args="${required_letter} ${other_letters}"
